name: flash_chat
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0-384.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - images/
   


